### ISSUE TITLE
MiniMessages in SyncProxy

### ISSUE THREAD

**Issue by DinoMarlir** [CloudNetService/CloudNet-v3#1384] opened 2024-04-05 21:00 UTC
### Describe the new feature

It would be very nice if you can use MiniMessages in SyncProxy

### Why do you need this feature?

Because MiniMessages (Adventure) are much better than the legacy '`§`-colors`

### Alternatives

You can just keep using '`§`-colors'.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment] 2024-05-03 12:41
Duplicate of #1343

**Closed as not planned** 2024-05-03 12:41 UTC
Labels: r: duplicate, t: feature request
