### ISSUE TITLE
Service startup freezes with cloudnet log

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#588] opened 2022-01-13 18:59 UTC
**Description of the bug:**

Sometimes, spigot services freeze during startup after printing
`de.dytanic.cloudnet.driver.network.exception.SilentDecoderException: Invalid var int`
to the Log/console.

There is no stacktrace, just this one line.
Nothing happens after this until manually deleting the service.

**Steps to reproduce this bug:**

**Expected behavior:**

No not print this and to not freeze.

**Environment and used hardware:**
CloudNet 3.4.2-RELEASE-99bc6b4
Java 17.0.1
Debian 10

**Comment by derklaro** [comment] 2022-01-13 19:09
Thanks for your report! I noticed that quite a few times in the last weeks in the support and I hope I was able to fix this for the next major release. I will keep this issue open however as i am unsure if the issue is really gone...

**Comment by derklaro** [comment] 2022-09-29 14:42
I was not able to reproduce the issue in v4 for a long time now, and never heard of a new report in v4. I'm going to close this issue as resolved, if the bug appears again feel free to open a new issue.

**Closed as completed by derklaro** 2022-09-29 14:42 UTC
Labels: t: bug, v: 4.X, s: we need to go deeper
