### ISSUE TITLE
CloudNet v4 RC9

### ISSUE THREAD

**Issue by NaturGamerYT** [CloudNetService/CloudNet-v3#1376] opened 2024-03-17 08:53 UTC
### Actions to reproduce

Run the `players online` command, it says 0 even when someone is in the game. The placeholder in the Tab is also not working. `players registered` also says that no one is registered.

### CloudNet version

CloudNet Blizzard 4.0.0-RC9 f6ca4c38
Discord: <https://discord.cloudnetservice.eu/>

ClusterId: 5130850b-****-4b7c-****-646f4f3f4aeb
NodeId: Node-1
Head-NodeId: Node-1
CPU usage: (P/S) 3.36/7.19/100%
Node services memory allocation (U/R/M): 6408/6408/8192 MB
Threads: 39
Heap usage: 56/256MB
JVM: Debian 17 (OpenJDK 64-Bit Server VM 17.0.10+7-Debian-1deb12u1)
Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment] 2024-03-17 08:56
Duplicate of #1310

**Closed as completed by 0utplay** 2024-03-17 08:56 UTC
Labels: t: bug, s: needs triage
