### ISSUE TITLE
Error when joining while using Luckperms

### ISSUE THREAD

**Issue by RootException** [CloudNetService/CloudNet-v3#1268] opened 2023-07-02 23:57 UTC
### Stacktrace

```
[23:43:16] [epollEventLoopGroup-3-1/WARN] [LuckPerms]: A permission check was made for player RootException - 3f180ea7-cb06-423a-b73b-445f02bbd17c, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
java.lang.Exception: null
	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:66) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.event.EventBus.post(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at eu.cloudnetservice.modules.bridge.platform.bungeecord.PendingConnectionProxiedPlayer.hasPermission(PendingConnectionProxiedPlayer.java:238) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyManagement.checkPlayerPermission(BungeeCordSyncProxyManagement.java:118) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyManagement.checkPlayerPermission(BungeeCordSyncProxyManagement.java:42) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.PlatformSyncProxyManagement.checkPlayerMaintenance(PlatformSyncProxyManagement.java:270) ~[?:?]
	at eu.cloudnetservice.modules.syncproxy.platform.bungee.BungeeCordSyncProxyListener.handleProxyLogin(BungeeCordSyncProxyListener.java:135) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.event.EventBus.post(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.connection.InitialHandler.finish(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.connection.InitialHandler.access$1700(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.connection.InitialHandler$5.done(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.connection.InitialHandler$5.done(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.http.HttpHandler.done(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.http.HttpHandler.channelRead0(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at net.md_5.bungee.http.HttpHandler.channelRead0(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.ssl.SslHandler.unwrap(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.ssl.SslHandler.decode(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:689c776:unknown]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Actions to reproduce

1. Install the Syncproxy module
2. Install LuckPerms into the Bungeecord template
3. Enable Maintenance
4. Join the network

### CloudNet version

```
[03.07 01:55:38.908] INFORMATION: CloudNet Blizzard 4.0.0-RC8 61a0ada8
[03.07 01:55:38.908] INFORMATION: Discord: <https://discord.cloudnetservice.eu/>
[03.07 01:55:38.909] INFORMATION:  
[03.07 01:55:38.909] INFORMATION: ClusterId: b1726bf9-****-4a54-****-911b44c5099c
[03.07 01:55:38.909] INFORMATION: NodeId: Node-1
[03.07 01:55:38.909] INFORMATION: Head-NodeId: Node-2
[03.07 01:55:38.909] INFORMATION: CPU usage: (P/S) 0,88/1,32/100%
[03.07 01:55:38.910] INFORMATION: Node services memory allocation (U/R/M): 2560/2560/49152 MB
[03.07 01:55:38.910] INFORMATION: Threads: 76
[03.07 01:55:38.910] INFORMATION: Heap usage: 60/256MB
[03.07 01:55:38.910] INFORMATION: JVM: Oracle Corporation 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190)
[03.07 01:55:38.910] INFORMATION: Update Repo: CloudNetService/launchermeta, Update Branch: beta
```

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment] 2023-12-31 13:35
The issue is resolved with #1308

**Closed as completed by 0utplay** 2023-12-31 13:35 UTC
Labels: t: bug, v: 4.X, s: confirmed
